### ISSUE TITLE
Persist data to Mongo => DocumentDB

### ISSUE THREAD

**Issue by codefoster** [codefoster/waterbug-site#2]

**Comment by DanielEgan** [comment]
Added logging data to MongoDB on MongoLabs.

**Comment by codefoster** [comment]
I thought we were going to use waterbug-data (the DocumentDB database in our Azure resource group) instead of MongoLabs

**Comment by DanielEgan** [comment]
We will, which is why I didn't close it.  Having trouble with documentDB .. I wanted everything else working first.

Sent from Nine

**Comment by DanielEgan** [comment]
DocumentDB support added.
