### ISSUE TITLE
Consider showing messages on the "/" route as they come in to help explain what's happening

### ISSUE THREAD

**Issue by codefoster** [codefoster/waterbug-site#4]
Right now you can browse to the "/" route of the server and it simply informs you that the socket server is up and running. It would be nice if that page would show a list of the messags that the socket server was processing as they came through so that when you're explaining the project in front of an audience you can easily explain it.

**Comment by DanielEgan** [comment]
This is complete but needs some styling.. The route and socket.io are implemented
